# compiler flags
CXX=g++
# -Wall (error thrower)
CXXFLAGS=-g -std=c++14 -Wall -Werror -pedantic -mwindows

SRC=$(wildcard *.cpp)
EXE=$(wildcard *.exe)
MAIN=decrypt.exe

def_comp:
	$(CXX) $(SRC) $(CXXFLAGS) -o $(MAIN)
	

	

